//Dummy header file used for translation generation...
#define DUMMY {
printf(_("Color settings"));
printf(_("Brightness and Contrast"));
printf(_("Brightness"));
printf(_("Contrast"));
printf(_("Magic Bright Mode"));
printf(_("Text"));
printf(_("Internet"));
printf(_("Game"));
printf(_("Sport"));
printf(_("Entertain"));
printf(_("Custom"));
printf(_("Dynamic Contrast"));
printf(_("Super Bright Mode"));
printf(_("One"));
printf(_("Two"));
printf(_("Three"));
printf(_("Auto Level (Needs a blank line to work)"));
printf(_("Backlight"));
printf(_("ECO Mode"));
printf(_("High"));
printf(_("Middle"));
printf(_("Low"));
printf(_("Auto"));
printf(_("f-Engine"));
printf(_("Normal"));
printf(_("User"));
printf(_("Text"));
printf(_("Movie"));
printf(_("Gamma"));
printf(_("Gamma"));
printf(_("-0.5"));
printf(_("-0.3"));
printf(_("-0.2"));
printf(_("-0.1"));
printf(_("0"));
printf(_("+0.1"));
printf(_("+0.2"));
printf(_("+0.3"));
printf(_("+0.4"));
printf(_("+0.5"));
printf(_("+0.6"));
printf(_("+0.7"));
printf(_("+0.9"));
printf(_("1.8"));
printf(_("2.0"));
printf(_("2.2"));
printf(_("2.4"));
printf(_("2.6"));
printf(_("Color maximum level"));
printf(_("Red maximum level"));
printf(_("Green maximum level"));
printf(_("Blue maximum level"));
printf(_("Color minimum level"));
printf(_("Red minimum level"));
printf(_("Green minimum level"));
printf(_("Blue minimum level"));
printf(_("Various color settings"));
printf(_("Hue"));
printf(_("Saturation"));
printf(_("Color curve adjust"));
printf(_("Color Preset"));
printf(_("Normal"));
printf(_("Custom"));
printf(_("Warm"));
printf(_("Cool"));
printf(_("Warm1"));
printf(_("Warm2"));
printf(_("Cool1"));
printf(_("Cool2"));
printf(_("Cool3"));
printf(_("Cool4"));
printf(_("Cool5"));
printf(_("Cool6"));
printf(_("Cool7"));
printf(_("sRGB"));
printf(_("4000K"));
printf(_("5000K"));
printf(_("6500K"));
printf(_("7500K"));
printf(_("8200K"));
printf(_("9300K"));
printf(_("10000K"));
printf(_("11500K"));
printf(_("Native"));
printf(_("User"));
printf(_("User 1"));
printf(_("User 2"));
printf(_("User 3"));
printf(_("User 4"));
printf(_("Easy"));
printf(_("Expert"));
printf(_("MagicColor"));
printf(_("Off"));
printf(_("Demo"));
printf(_("Full"));
printf(_("Intelligent"));
printf(_("Color temperature"));
printf(_("Color Return"));
printf(_("Position and size"));
printf(_("Position"));
printf(_("Horizontal Position"));
printf(_("Vertical Position"));
printf(_("Size"));
printf(_("Horizontal Size"));
printf(_("Vertical Size"));
printf(_("Automatic adjustments"));
printf(_("Auto Size Center"));
printf(_("Enable"));
printf(_("Disable"));
printf(_("Automatically adjust"));
printf(_("H/V Position"));
printf(_("Clock and clock phase"));
printf(_("H/V Position (fast mode)"));
printf(_("Geometry"));
printf(_("Pincushion"));
printf(_("Horizontal Pincushion"));
printf(_("Horizontal Pincushion Balance"));
printf(_("Vertical Pincushion"));
printf(_("Vertical Pincushion Balance"));
printf(_("Center Pincushion"));
printf(_("Linearity"));
printf(_("Horizontal Linearity"));
printf(_("Horizontal Linearity Balance"));
printf(_("Vertical Linearity"));
printf(_("Vertical Linearity Balance"));
printf(_("Misconvergence"));
printf(_("Horizontal Misconvergence"));
printf(_("Vertical Misconvergence"));
printf(_("Vertical Top Misconvergence"));
printf(_("Vertical Bottom Misconvergence"));
printf(_("General distortion"));
printf(_("Parallelogram Distortion (Key Balance)"));
printf(_("Trapezoidal Distortion (Key)"));
printf(_("Corners distortion"));
printf(_("Top Corner Distortion Control"));
printf(_("Top Corner Distortion Balance"));
printf(_("Bottom Corner Distortion Control"));
printf(_("Bottom Corner Distortion Balance"));
printf(_("Rotation"));
printf(_("Rotation (Tilt)"));
printf(_("Screen purity"));
printf(_("Moire"));
printf(_("Horizontal Moire"));
printf(_("Vertical Moire"));
printf(_("Image setup"));
printf(_("Focus"));
printf(_("Image Lock Coarse (Clock)"));
printf(_("Image Lock Fine (Clock Phase)"));
printf(_("Corners purity"));
printf(_("Top left screen purity"));
printf(_("Top right screen purity"));
printf(_("Bottom left screen purity"));
printf(_("Bottom right screen purity"));
printf(_("Various"));
printf(_("Landing Adjust (RGB alignment)"));
printf(_("Sharpness"));
printf(_("Others"));
printf(_("Restore defaults"));
printf(_("Restore Factory Defaults"));
printf(_("Restore Brightness and Contrast"));
printf(_("Restore Factory Default Geometry"));
printf(_("Restore Factory Default Color"));
printf(_("Restore Factory Default Position"));
printf(_("Restore Factory Default Size"));
printf(_("Restore Factory Default Size and Position"));
printf(_("Settings"));
printf(_("Save Current Settings"));
printf(_("Restore Factory Settings"));
printf(_("Audio"));
printf(_("Audio Speaker Volume Adjust"));
printf(_("Audio Microphone Volume Adjust"));
printf(_("Mute"));
printf(_("Mute"));
printf(_("Normal"));
printf(_("Degauss"));
printf(_("Degauss"));
printf(_("Secondary Degauss"));
printf(_("OSD"));
printf(_("On Screen Display"));
printf(_("Disable"));
printf(_("Enable"));
printf(_("Enable only brightness/contrast settings"));
printf(_("On Screen Display (Samsung)"));
printf(_("Disable"));
printf(_("Enable"));
printf(_("OSD Orientation"));
printf(_("Landscape"));
printf(_("Portrait"));
printf(_("Language select"));
printf(_("English"));
printf(_("French"));
printf(_("German"));
printf(_("Italian"));
printf(_("Russian"));
printf(_("Spanish"));
printf(_("Swedish"));
printf(_("Chinese"));
printf(_("Dutch"));
printf(_("Japanese"));
printf(_("Input settings"));
printf(_("Input level Select"));
printf(_("Display Resolution Notifier"));
printf(_("On"));
printf(_("Off"));
printf(_("Input Source Select"));
printf(_("Analog"));
printf(_("Digital"));
printf(_("Autoselect Input Source"));
printf(_("Automatic"));
printf(_("Manual"));
printf(_("Power control"));
printf(_("DPMS Control"));
printf(_("On"));
printf(_("Standby"));
printf(_("Power control"));
printf(_("Off"));
printf(_("On"));
printf(_("Buttons and leds"));
printf(_("Custom key"));
printf(_("MagicBright"));
printf(_("MagicColor"));
printf(_("Automatic setup"));
printf(_("Input Source Select"));
printf(_("Color Tone"));
printf(_("Power LED"));
printf(_("Off"));
printf(_("On"));
printf(_("Testing"));
printf(_("0x0X"));
printf(_("Control 0x02"));
printf(_("Control 0x03"));
printf(_("Control 0x04"));
printf(_("Control 0x05"));
printf(_("Control 0x06"));
printf(_("Control 0x07"));
printf(_("Control 0x08"));
printf(_("Control 0x09"));
printf(_("Control 0x0A"));
printf(_("Control 0x0B"));
printf(_("Control 0x0C"));
printf(_("Control 0x0D"));
printf(_("Control 0x0E"));
printf(_("Control 0x0F"));
printf(_("0x1X"));
printf(_("Control 0x10"));
printf(_("Control 0x11"));
printf(_("Control 0x12"));
printf(_("Control 0x13"));
printf(_("Control 0x14"));
printf(_("Control 0x15"));
printf(_("Control 0x16"));
printf(_("Control 0x17"));
printf(_("Control 0x18"));
printf(_("Control 0x19"));
printf(_("Control 0x1A"));
printf(_("Control 0x1B"));
printf(_("Control 0x1C"));
printf(_("Control 0x1D"));
printf(_("Control 0x1E"));
printf(_("Control 0x1F"));
printf(_("0x2X"));
printf(_("Control 0x20"));
printf(_("Control 0x21"));
printf(_("Control 0x22"));
printf(_("Control 0x23"));
printf(_("Control 0x24"));
printf(_("Control 0x25"));
printf(_("Control 0x26"));
printf(_("Control 0x27"));
printf(_("Control 0x28"));
printf(_("Control 0x29"));
printf(_("Control 0x2A"));
printf(_("Control 0x2B"));
printf(_("Control 0x2C"));
printf(_("Control 0x2D"));
printf(_("Control 0x2E"));
printf(_("Control 0x2F"));
printf(_("0x3X"));
printf(_("Control 0x30"));
printf(_("Control 0x31"));
printf(_("Control 0x32"));
printf(_("Control 0x33"));
printf(_("Control 0x34"));
printf(_("Control 0x35"));
printf(_("Control 0x36"));
printf(_("Control 0x37"));
printf(_("Control 0x38"));
printf(_("Control 0x39"));
printf(_("Control 0x3A"));
printf(_("Control 0x3B"));
printf(_("Control 0x3C"));
printf(_("Control 0x3D"));
printf(_("Control 0x3E"));
printf(_("Control 0x3F"));
printf(_("0x4X"));
printf(_("Control 0x40"));
printf(_("Control 0x41"));
printf(_("Control 0x42"));
printf(_("Control 0x43"));
printf(_("Control 0x44"));
printf(_("Control 0x45"));
printf(_("Control 0x46"));
printf(_("Control 0x47"));
printf(_("Control 0x48"));
printf(_("Control 0x49"));
printf(_("Control 0x4A"));
printf(_("Control 0x4B"));
printf(_("Control 0x4C"));
printf(_("Control 0x4D"));
printf(_("Control 0x4E"));
printf(_("Control 0x4F"));
printf(_("0x5X"));
printf(_("Control 0x50"));
printf(_("Control 0x51"));
printf(_("Control 0x52"));
printf(_("Control 0x53"));
printf(_("Control 0x54"));
printf(_("Control 0x55"));
printf(_("Control 0x56"));
printf(_("Control 0x57"));
printf(_("Control 0x58"));
printf(_("Control 0x59"));
printf(_("Control 0x5A"));
printf(_("Control 0x5B"));
printf(_("Control 0x5C"));
printf(_("Control 0x5D"));
printf(_("Control 0x5E"));
printf(_("Control 0x5F"));
printf(_("0x6X"));
printf(_("Control 0x60"));
printf(_("Control 0x61"));
printf(_("Control 0x62"));
printf(_("Control 0x63"));
printf(_("Control 0x64"));
printf(_("Control 0x65"));
printf(_("Control 0x66"));
printf(_("Control 0x67"));
printf(_("Control 0x68"));
printf(_("Control 0x69"));
printf(_("Control 0x6A"));
printf(_("Control 0x6B"));
printf(_("Control 0x6C"));
printf(_("Control 0x6D"));
printf(_("Control 0x6E"));
printf(_("Control 0x6F"));
printf(_("0x7X"));
printf(_("Control 0x70"));
printf(_("Control 0x71"));
printf(_("Control 0x72"));
printf(_("Control 0x73"));
printf(_("Control 0x74"));
printf(_("Control 0x75"));
printf(_("Control 0x76"));
printf(_("Control 0x77"));
printf(_("Control 0x78"));
printf(_("Control 0x79"));
printf(_("Control 0x7A"));
printf(_("Control 0x7B"));
printf(_("Control 0x7C"));
printf(_("Control 0x7D"));
printf(_("Control 0x7E"));
printf(_("Control 0x7F"));
printf(_("0x8X"));
printf(_("Control 0x80"));
printf(_("Control 0x81"));
printf(_("Control 0x82"));
printf(_("Control 0x83"));
printf(_("Control 0x84"));
printf(_("Control 0x85"));
printf(_("Control 0x86"));
printf(_("Control 0x87"));
printf(_("Control 0x88"));
printf(_("Control 0x89"));
printf(_("Control 0x8A"));
printf(_("Control 0x8B"));
printf(_("Control 0x8C"));
printf(_("Control 0x8D"));
printf(_("Control 0x8E"));
printf(_("Control 0x8F"));
printf(_("0x9X"));
printf(_("Control 0x90"));
printf(_("Control 0x91"));
printf(_("Control 0x92"));
printf(_("Control 0x93"));
printf(_("Control 0x94"));
printf(_("Control 0x95"));
printf(_("Control 0x96"));
printf(_("Control 0x97"));
printf(_("Control 0x98"));
printf(_("Control 0x99"));
printf(_("Control 0x9A"));
printf(_("Control 0x9B"));
printf(_("Control 0x9C"));
printf(_("Control 0x9D"));
printf(_("Control 0x9E"));
printf(_("Control 0x9F"));
printf(_("0xAX"));
printf(_("Control 0xA0"));
printf(_("Control 0xA1"));
printf(_("Control 0xA2"));
printf(_("Control 0xA3"));
printf(_("Control 0xA4"));
printf(_("Control 0xA5"));
printf(_("Control 0xA6"));
printf(_("Control 0xA7"));
printf(_("Control 0xA8"));
printf(_("Control 0xA9"));
printf(_("Control 0xAA"));
printf(_("Control 0xAB"));
printf(_("Control 0xAC"));
printf(_("Control 0xAD"));
printf(_("Control 0xAE"));
printf(_("Control 0xAF"));
printf(_("0xBX"));
printf(_("Control 0xB0"));
printf(_("Control 0xB1"));
printf(_("Control 0xB2"));
printf(_("Control 0xB3"));
printf(_("Control 0xB4"));
printf(_("Control 0xB5"));
printf(_("Control 0xB6"));
printf(_("Control 0xB7"));
printf(_("Control 0xB8"));
printf(_("Control 0xB9"));
printf(_("Control 0xBA"));
printf(_("Control 0xBB"));
printf(_("Control 0xBC"));
printf(_("Control 0xBD"));
printf(_("Control 0xBE"));
printf(_("Control 0xBF"));
printf(_("0xCX"));
printf(_("Control 0xC0"));
printf(_("Control 0xC1"));
printf(_("Control 0xC2"));
printf(_("Control 0xC3"));
printf(_("Control 0xC4"));
printf(_("Control 0xC5"));
printf(_("Control 0xC6"));
printf(_("Control 0xC7"));
printf(_("Control 0xC8"));
printf(_("Control 0xC9"));
printf(_("Control 0xCA"));
printf(_("Control 0xCB"));
printf(_("Control 0xCC"));
printf(_("Control 0xCD"));
printf(_("Control 0xCE"));
printf(_("Control 0xCF"));
printf(_("0xDX"));
printf(_("Control 0xD0"));
printf(_("Control 0xD1"));
printf(_("Control 0xD2"));
printf(_("Control 0xD3"));
printf(_("Control 0xD4"));
printf(_("Control 0xD5"));
printf(_("Control 0xD6"));
printf(_("Control 0xD7"));
printf(_("Control 0xD8"));
printf(_("Control 0xD9"));
printf(_("Control 0xDA"));
printf(_("Control 0xDB"));
printf(_("Control 0xDC"));
printf(_("Control 0xDD"));
printf(_("Control 0xDE"));
printf(_("Control 0xDF"));
printf(_("0xEX"));
printf(_("Control 0xE0"));
printf(_("Control 0xE1"));
printf(_("Control 0xE2"));
printf(_("Control 0xE3"));
printf(_("Control 0xE4"));
printf(_("Control 0xE5"));
printf(_("Control 0xE6"));
printf(_("Control 0xE7"));
printf(_("Control 0xE8"));
printf(_("Control 0xE9"));
printf(_("Control 0xEA"));
printf(_("Control 0xEB"));
printf(_("Control 0xEC"));
printf(_("Control 0xED"));
printf(_("Control 0xEE"));
printf(_("Control 0xEF"));
printf(_("0xFX"));
printf(_("Control 0xF0"));
printf(_("Control 0xF1"));
printf(_("Control 0xF2"));
printf(_("Control 0xF3"));
printf(_("Control 0xF4"));
printf(_("Control 0xF5"));
printf(_("Control 0xF6"));
printf(_("Control 0xF7"));
printf(_("Control 0xF8"));
printf(_("Control 0xF9"));
printf(_("Control 0xFA"));
printf(_("Control 0xFB"));
printf(_("Control 0xFC"));
printf(_("Control 0xFD"));
printf(_("Control 0xFE"));
printf(_("Control 0xFF"));
}
